Repository ls1intum/Apollon, pull requests merged in 2022-05, with the labels that each got.

#218 Development: Fix SVG attribute injection vulnerability
  src/main/scenes/svg.tsx
Labels: security, ready for merge

#227 fix: ThemedLine in dark mode
  src/main/components/theme/themedComponents.ts
  src/tests/packages/uml-use-case-diagram/uml-use-case-actor/__snapshots__/uml-use-case-actor-component-test.tsx.snap
Labels: ready for merge

#234 ``Development``: Fix for coloring elements in Apollon
  src/main/packages/common/uml-classifier/uml-classifier-component.tsx
  src/main/packages/common/uml-classifier/uml-classifier-member-component.tsx
  src/main/packages/common/uml-component/uml-component-component.tsx
  src/main/packages/common/uml-interface-provided/uml-interface-provided-component.tsx
  src/main/packages/flowchart/flowchart-decision/flowchart-decision-component.tsx
  src/main/packages/flowchart/flowchart-function-call/flowchart-function-call-component.tsx
  src/main/packages/flowchart/flowchart-input-output/flowchart-input-output-component.tsx
  src/main/packages/flowchart/flowchart-process/flowchart-process-component.tsx
  src/main/packages/flowchart/flowchart-terminal/flowchart-terminal-component.tsx
  src/main/packages/syntax-tree/syntax-tree-nonterminal/syntax-tree-nonterminal-component.tsx
  src/main/packages/syntax-tree/syntax-tree-terminal/syntax-tree-terminal-component.tsx
  src/main/packages/uml-activity-diagram/uml-activity-action-node/uml-activity-action-node-component.tsx
  src/main/packages/uml-activity-diagram/uml-activity-merge-node/uml-activity-merge-node-component.tsx
  src/main/packages/uml-activity-diagram/uml-activity-object-node/uml-activity-object-node-component.tsx
  src/main/packages/uml-activity-diagram/uml-activity/uml-activity-component.tsx
  src/main/packages/uml-class-diagram/uml-class-package/uml-class-package-component.tsx
  src/main/packages/uml-deployment-diagram/uml-deployment-artifact/uml-deployment-artifact-component.tsx
  src/main/packages/uml-deployment-diagram/uml-deployment-node/uml-deployment-node-component.tsx
  src/main/packages/uml-petri-net/uml-petri-net-transition/uml-petri-net-transition-component.tsx
  src/main/packages/uml-reachability-graph/uml-reachability-graph-marking/uml-reachability-graph-marking-component.tsx
  src/main/packages/uml-use-case-diagram/uml-use-case-actor/uml-use-case-actor-component.tsx
  src/main/packages/uml-use-case-diagram/uml-use-case/uml-use-case-component.tsx
  src/tests/unit/packages/uml-component-diagram/uml-component-provided-interface/__snapshots__/uml-component-provided-interface-component-test.tsx.snap
  src/tests/unit/packages/uml-deployment-diagram/uml-deployment-provided-interface/__snapshots__/uml-deployment-provided-interface-component-test.tsx.snap
Labels: bug
